### ISSUE TITLE
(SP: 2 ) Add validation for General info step

### ISSUE THREAD

**Issue by vlad-khrychov** [Space2Study-Project/Space2Study-FrontEnd#159]
UserStory: #77, #78 
Blocked by: #154 

## Description
Add validation to required fields in General Info step for both student and tutor steppers

## Design 

![Image](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/67462207/31621afa-e697-4a88-93db-7f6dfba43058)

## Acceptance Criteria
- [x] First name and Last name fields must be required and show an error when user removed text from them.
- [x] Country and city have to be pulled from server on input focus
- [x] Length of additional info can't be more than 100 symbols and block texting when it reached limit
- [x] When there are errors in required fields stepper can't be finished

**Comment by LeonidShamarin** [comment]
Must write test for it now.
