### ISSUE TITLE
(SP: 2 ) show error message to User if an error occurs while fetching categories in the SubjectsStep component

### ISSUE THREAD

**Issue by marianamartsy** [Space2Study-Project/Space2Study-FrontEnd#169]
Description:

When fetching categories in the SubjectsStep and General step component, if an error occurs, the current implementation logs the error to the console. To enhance user experience, it would be beneficial to display an error message instead of logging to the console.

Tasks:
Display Error to User: When an error occurs during the fetching of categories, update the UI to show the error message.

Testing: Write tests to verify that the error handling works as expected.

**Comment by pbelokon** [comment]
@marianamartsy  Can I work on this ?

**Comment by marianamartsy** [comment]
@pbelokon Hi. Thank you but no, this is a learning project.

**Comment by pbelokon** [comment]
oh I see thanks for letting me know
