### ISSUE TITLE
(SP: 2) Add Language step

### ISSUE THREAD

**Issue by vlad-khrychov** [Space2Study-Project/Space2Study-FrontEnd#177]
UserStory: #73, #74

## Description
Implement add photo and select field in the language info step for both student and tutor steppers

## Design 
![Image](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/67462207/225742e7-e338-4583-99fe-783e09942174)
## Acceptance Criteria
- [x] When user click on select it should fetch existing languages from server
- [x] When user click on criss-cross it should remove select field value

**Comment by marianamartsy** [comment]
We reviewed the code and found that currently the list of languages is not being fetched from the backend but rather from a constants.js file.
